### ISSUE TITLE
Pre-Publishing Tests

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-kubernetes-intro#54]
Pre-Publishing Tests

- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs) of the guide on test site, ie, qa-guides
- [x] Clone repo and test finish directory with no error
- [x] Follow the guide to test that it is working

**Comment by justineechen** [comment]
When visiting http://[hostname]:31000/api/name after scaling deployment, the name doesn't change on the browser but it does change when I run `curl` on the link.

**Comment by evelinec** [comment]
I move the last point in the checklist to "Post-Publishing" as only then we'd have the working ol.io link.

**Comment by gkwan-ibm** [comment]
- at this moment, no change
- the guide will add command to show # of running instances (dockers) before and after scaling
